project_id = "xitliskomnkgspqgmtud"

[functions.research-company]
verify_jwt = false

[functions.fetch-company-details]
verify_jwt = false

[functions.send-ticket-email]
verify_jwt = false

[functions.send-ticket-closure-email]
verify_jwt = false

[functions.send-ticket-query-email]
verify_jwt = false
